/*
 * Copyright 2017 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package iht.constants

import javax.inject.{Inject, Singleton}

import iht.config.IhtPropertiesReader
import org.joda.time.LocalDate
import play.api.Logger

/**
  * Created by yasar on 25/11/15.
  */
@Singleton
class IhtProperties @Inject() (val ihtPropertiesReader: IhtPropertiesReader) {
  lazy val validCountryCodes: Array[String] = ihtPropertiesReader.getPropertyAsStringArray("validCountryCodes")
  lazy val ukIsoCountryCode: String = ihtPropertiesReader.getProperty("ukIsoCountryCode")
  lazy val dateFormatForDisplay: String = ihtPropertiesReader.getProperty("dateFormatForDisplay")
  lazy val maxCoExecutors: Int = ihtPropertiesReader.getPropertyAsInt("maxCoExecutors")
  lazy val maxNameLength: Int = ihtPropertiesReader.getPropertyAsInt("maxNameLength")
  lazy val hyphenateNamesLength: Int = ihtPropertiesReader.getPropertyAsInt("hyphenateNamesLength")
  lazy val validationMaxLengthAddresslines: Int = ihtPropertiesReader.getPropertyAsInt("validationMaxLengthAddresslines")
  lazy val validationMaxLengthPostcode: Int = ihtPropertiesReader.getPropertyAsInt("validationMaxLengthPostcode")
  lazy val validationMaxLengthFirstName: Int = ihtPropertiesReader.getPropertyAsInt("validationMaxLengthFirstName")
  lazy val validationMaxLengthLastName: Int = ihtPropertiesReader.getPropertyAsInt("validationMaxLengthLastName")
  lazy val validationMaxLengthNINO: Int = ihtPropertiesReader.getPropertyAsInt("validationMaxLengthNINO")
  lazy val validationMinLengthNINO: Int = ihtPropertiesReader.getPropertyAsInt("validationMinLengthNINO")
  lazy val validationMaxLengthPhoneNo: Int = ihtPropertiesReader.getPropertyAsInt("validationMaxLengthPhoneNo")
  lazy val validationMaxCharityNumberLength: Int = ihtPropertiesReader.getPropertyAsInt("validationMaxCharityNumberLength")
  lazy val validationMinCharityNumberLength: Int = ihtPropertiesReader.getPropertyAsInt("validationMinCharityNumberLength")
  lazy val validationMaxLengthCharityName: Int = ihtPropertiesReader.getPropertyAsInt("validationMaxLengthCharityName")
  lazy val validationMaxLengthQualifyingBodyName: Int = ihtPropertiesReader.getPropertyAsInt("validationMaxLengthQualifyingBodyName")

  lazy val validationTrustMaxValue: BigDecimal = ihtPropertiesReader.getPropertyAsBigDecimal("validationTrustMaxValue")
  lazy val validationForeignAssetMaxValue: BigDecimal = ihtPropertiesReader.getPropertyAsBigDecimal("validationForeignAssetMaxValue")
  lazy val validationTotalAssetMaxValue: BigDecimal = ihtPropertiesReader.getPropertyAsBigDecimal("validationTotalAssetMaxValue")
  lazy val tnrbThresholdLimit: BigDecimal = ihtPropertiesReader.getPropertyAsBigDecimal("tnrbThresholdLimit")
  lazy val transferredNilRateBand: BigDecimal = ihtPropertiesReader.getPropertyAsBigDecimal("transferredNilRateBand")
  lazy val exemptionsThresholdValue: BigDecimal = ihtPropertiesReader.getPropertyAsBigDecimal("exemptionsThresholdValue")
  lazy val giftsMaxValue: BigDecimal = ihtPropertiesReader.getPropertyAsBigDecimal("giftsMaxValue")
  lazy val taxThreshold: BigDecimal = ihtPropertiesReader.getPropertyAsBigDecimal("taxThreshold")
  lazy val grossEstateLimit: BigDecimal = ihtPropertiesReader.getPropertyAsBigDecimal("grossEstateLimit")

  lazy val applicantCountryEnglandOrWales: String = ihtPropertiesReader.getProperty("applicantCountryEnglandOrWales")
  lazy val applicantCountryScotland: String = ihtPropertiesReader.getProperty("applicantCountryScotland")
  lazy val applicantCountryNorthernIreland: String = ihtPropertiesReader.getProperty("applicantCountryNorthernIreland")
  lazy val applicantCountryOther: String = ihtPropertiesReader.getProperty("applicantCountryOther")
  lazy val roleLeadExecutor: String = ihtPropertiesReader.getProperty("roleLeadExecutor")
  lazy val roleExecutor: String = ihtPropertiesReader.getProperty("roleExecutor")
  lazy val roleAdministrator: String = ihtPropertiesReader.getProperty("roleAdministrator")
  lazy val domicileEnglandOrWales: String = ihtPropertiesReader.getProperty("domicileEnglandOrWales")
  lazy val domicileScotland: String = ihtPropertiesReader.getProperty("domicileScotland")
  lazy val domicileNorthernIreland: String = ihtPropertiesReader.getProperty("domicileNorthernIreland")
  lazy val domicileOther: String = ihtPropertiesReader.getProperty("domicileOther")
  lazy val statusMarried: String = ihtPropertiesReader.getProperty("statusMarried")
  lazy val statusSingle: String = ihtPropertiesReader.getProperty("statusSingle")
  lazy val statusDivorced: String = ihtPropertiesReader.getProperty("statusDivorced")
  lazy val statusWidowed: String = ihtPropertiesReader.getProperty("statusWidowed")
  lazy val linkGovUkIht: String = ihtPropertiesReader.getProperty("linkGovUkIht")
  lazy val linkRegistrationKickOut: String = ihtPropertiesReader.getProperty("linkRegistrationKickOut")
  lazy val linkEstateReportKickOut: String = ihtPropertiesReader.getProperty("linkEstateReportKickOut")
  lazy val linkIHTGifts: String = ihtPropertiesReader.getProperty("linkIHTGifts")
  lazy val linkGovUk: String = ihtPropertiesReader.getProperty("linkGovUk")
  lazy val linkIHT401: String = ihtPropertiesReader.getProperty("linkIHT401")
  lazy val linkExitToGovUKIHTForms: String = ihtPropertiesReader.getProperty("linkExitToGovUKIHTForms")
  lazy val linkScottishCourtAndTribunal: String = ihtPropertiesReader.getProperty("linkScottishCourtAndTribunal")
  lazy val linkIHT205: String = ihtPropertiesReader.getProperty("linkIHT205")
  lazy val linkContactHMRC: String = ihtPropertiesReader.getProperty("linkContactHMRC")
  lazy val linkLandRegistry: String = ihtPropertiesReader.getProperty("linkLandRegistry")
  lazy val charityLink: String = ihtPropertiesReader.getProperty("charityLink")
  lazy val correctiveAccountsLink: String = ihtPropertiesReader.getProperty("correctiveAccountLink")
  lazy val giftsStartDay: Int = ihtPropertiesReader.getPropertyAsInt("giftsStartDay")
  lazy val giftsStartMonth: Int = ihtPropertiesReader.getPropertyAsInt("giftsStartMonth")
  lazy val giftsYears: Int = ihtPropertiesReader.getPropertyAsInt("giftsYears")
  lazy val ownershipDeceasedOnly: String = ihtPropertiesReader.getProperty("ownershipDeceasedOnly")
  lazy val ownershipJoint: String = ihtPropertiesReader.getProperty("ownershipJoint")
  lazy val ownershipInCommon: String = ihtPropertiesReader.getProperty("ownershipInCommon")
  lazy val tenureFreehold: String = ihtPropertiesReader.getProperty("tenureFreehold")
  lazy val tenureLeasehold: String = ihtPropertiesReader.getProperty("tenureLeasehold")
  lazy val propertyTypeDeceasedHome: String = ihtPropertiesReader.getProperty("propertyTypeDeceasedHome")
  lazy val propertyTypeOtherResidentialBuilding: String = ihtPropertiesReader.getProperty("propertyTypeOtherResidentialBuilding")
  lazy val propertyTypeNonResidential: String = ihtPropertiesReader.getProperty("propertyTypeNonResidential")
  lazy val questionnaireEasyToUseVeryEasy: String = ihtPropertiesReader.getProperty("questionnaireEasyToUseVeryEasy")
  lazy val questionnaireEasyToUseEasy: String = ihtPropertiesReader.getProperty("questionnaireEasyToUseEasy")
  lazy val questionnaireEasyToUseNeither: String = ihtPropertiesReader.getProperty("questionnaireEasyToUseNeither")
  lazy val questionnaireEasyToUseDifficult: String = ihtPropertiesReader.getProperty("questionnaireEasyToUseDifficult")
  lazy val questionnaireEasyToUseVeryDifficult: String = ihtPropertiesReader.getProperty("questionnaireEasyToUseVeryDifficult")
  lazy val questionnaireFeelingAboutExperienceVerySatisfied: String = ihtPropertiesReader.getProperty("questionnaireFeelAboutYourExperienceVerySatisfied")
  lazy val questionnaireFeelingAboutExperienceSatisfied: String = ihtPropertiesReader.getProperty("questionnaireFeelAboutYourExperienceSatisfied")
  lazy val questionnaireFeelingAboutExperienceNeither: String = ihtPropertiesReader.getProperty("questionnaireFeelAboutYourExperienceNeither")
  lazy val questionnaireFeelingAboutExperienceDissatisfied: String = ihtPropertiesReader.getProperty("questionnaireFeelAboutYourExperienceDissatisfied")
  lazy val questionnaireFeelingAboutExperienceVeryDissatisfied: String = ihtPropertiesReader.getProperty("questionnaireFeelAboutYourExperienceVeryDissatisfied")
  lazy val giftsInYearMaxExemptionsValue: Int = ihtPropertiesReader.getPropertyAsInt("giftsInYearMaxExemptionsValue")
  lazy val maximumAdditionalCoExecutors: Int = ihtPropertiesReader.getPropertyAsInt("maximumAdditionalCoExecutors")
  lazy val dateOfDeathMinValidationDate: LocalDate = ihtPropertiesReader.getPropertyAsDate("dateOfDeathMinValidationDate")
  lazy val dateOfDeathMaxValidationDate: LocalDate = ihtPropertiesReader.getPropertyAsDate("dateOfDeathMaxValidationDate")
  lazy val dateOfPredeceasedForTnrbEligibility: LocalDate = ihtPropertiesReader.getPropertyAsDate("dateOfPredeceasedForTnrbEligibility")
  lazy val dateOfCivilPartnershipInclusion: LocalDate = ihtPropertiesReader.getPropertyAsDate("dateOfCivilPartnershipInclusion")

  lazy val ETMPAssetCodeMoney:String = ihtPropertiesReader.getProperty("etmpAssetCodeMoney")
  lazy val ETMPAssetCodeHouseHold:String = ihtPropertiesReader.getProperty("etmpAssetCodeHouseHold")
  lazy val ETMPAssetCodePrivatePension:String = ihtPropertiesReader.getProperty("etmpAssetCodePrivatePension")
  lazy val ETMPAssetCodeStockShareNotListed:String = ihtPropertiesReader.getProperty("etmpAssetCodeStockShareNotListed")
  lazy val ETMPAssetCodeStockShareListed:String = ihtPropertiesReader.getProperty("etmpAssetCodeStockShareListed")
  lazy val ETMPAssetCodeInsurancePolicy:String = ihtPropertiesReader.getProperty("etmpAssetCodeInsurancePolicy")
  lazy val ETMPAssetCodeBusinessInterest:String = ihtPropertiesReader.getProperty("etmpAssetCodeBusinessInterest")
  lazy val ETMPAssetCodeNominatedAsset:String = ihtPropertiesReader.getProperty("etmpAssetCodeNominatedAsset")
  lazy val ETMPAssetCodeForeignAsset:String = ihtPropertiesReader.getProperty("etmpAssetCodeForeignAsset")
  lazy val ETMPAssetCodeMoneyOwed:String = ihtPropertiesReader.getProperty("etmpAssetCodeMoneyOwed")
  lazy val ETMPAssetCodeOtherAsset:String = ihtPropertiesReader.getProperty("etmpAssetCodeOtherAsset")
  lazy val ETMPAssetCodeTrust:String = ihtPropertiesReader.getProperty("etmpAssetCodeTrust")
  lazy val ETMPAssetCodeGift:String = ihtPropertiesReader.getProperty("etmpAssetCodeGift")
  lazy val ETMPAssetCodeDeceasedsHome:String = ihtPropertiesReader.getProperty("etmpAssetCodeDeceasedsHome")

  lazy val ETMPExemptionTypeGNCP: String = ihtPropertiesReader.getProperty("etmpExemptionTypeGNCP")
  lazy val ETMPExemptionTypeSpouse: String = ihtPropertiesReader.getProperty("etmpExemptionTypeSpouse")
  lazy val ETMPExemptionTypeCharity: String = ihtPropertiesReader.getProperty("etmpExemptionTypeCharity")

  lazy val DateRangeMonths: Integer = ihtPropertiesReader.getPropertyAsInt("dateRangeMonths")

  lazy val pdfStaticHeaders: Seq[(String, String)] = {
    val headers = ihtPropertiesReader.getPropertyAsSeqStringTuples("pdfStaticHeaders")
    Logger.debug("PDF static headers read in from property file:" + headers)
    headers
  }

  /*
  * Fragment Identifiers
  * Used to return user to where they were in a list
  * */
  lazy val AppSectionPropertiesID =  ihtPropertiesReader.getProperty("AppSectionPropertiesID")
  lazy val AppSectionMoneyID =  ihtPropertiesReader.getProperty("AppSectionMoneyID")
  lazy val AppSectionHouseholdID =  ihtPropertiesReader.getProperty("AppSectionHouseholdID")
  lazy val AppSectionVehiclesID =  ihtPropertiesReader.getProperty("AppSectionVehiclesID")
  lazy val AppSectionPrivatePensionID =  ihtPropertiesReader.getProperty("AppSectionPrivatePensionID")
  lazy val AppSectionStockAndShareID =  ihtPropertiesReader.getProperty("AppSectionStockAndShareID")
  lazy val AppSectionInsurancePolicyID =  ihtPropertiesReader.getProperty("AppSectionInsurancePolicyID")
  lazy val AppSectionBusinessInterestID =  ihtPropertiesReader.getProperty("AppSectionBusinessInterestID")
  lazy val AppSectionNominatedID =  ihtPropertiesReader.getProperty("AppSectionNominatedID")
  lazy val AppSectionHeldInTrustID =  ihtPropertiesReader.getProperty("AppSectionHeldInTrustID")
  lazy val AppSectionForeignID =  ihtPropertiesReader.getProperty("AppSectionForeignID")
  lazy val AppSectionMoneyOwedID =  ihtPropertiesReader.getProperty("AppSectionMoneyOwedID")
  lazy val AppSectionOtherID =  ihtPropertiesReader.getProperty("AppSectionOtherID")
  lazy val GiftsGivenAwayQuestionID =  ihtPropertiesReader.getProperty("GiftsGivenAwayQuestionID")
  lazy val GiftsReservationBenefitSectionID =  ihtPropertiesReader.getProperty("GiftsReservationBenefitSectionID")
  lazy val GiftsReservationBenefitQuestionID = ihtPropertiesReader.getProperty("GiftsReservationBenefitQuestionID")
  lazy val GiftsSevenYearsSectionID =  ihtPropertiesReader.getProperty("GiftsSevenYearsSectionID")
  lazy val GiftsSevenYearsQuestionID =  ihtPropertiesReader.getProperty("GiftsSevenYearsQuestionID")
  lazy val GiftsSevenYearsQuestionID2 =  ihtPropertiesReader.getProperty("GiftsSevenYearsQuestionID2")
  lazy val GiftsValueOfGiftsSectionID =  ihtPropertiesReader.getProperty("GiftsValueOfGiftsSectionID")
  lazy val GiftsValueOfGiftsQuestionID =  ihtPropertiesReader.getProperty("GiftsValueOfGiftsQuestionID")
  lazy val GiftsValueDetailID =  ihtPropertiesReader.getProperty("GiftsValueDetailID")
  lazy val DebtsMortgagesID =  ihtPropertiesReader.getProperty("DebtsMortgagesID")
  lazy val DebtsFuneralExpensesID =  ihtPropertiesReader.getProperty("DebtsFuneralExpensesID")
  lazy val DebtsOwedFromTrustID =  ihtPropertiesReader.getProperty("DebtsOwedFromTrustID")
  lazy val DebtsOwedOutsideUKID =  ihtPropertiesReader.getProperty("DebtsOwedOutsideUKID")
  lazy val DebtsOwedJointlyID =  ihtPropertiesReader.getProperty("DebtsOwedJointlyID")
  lazy val DebtsOtherID =  ihtPropertiesReader.getProperty("DebtsOtherID")
  lazy val InsurancePayingToDeceasedSectionID =  ihtPropertiesReader.getProperty("InsurancePayingToDeceasedSectionID")
  lazy val InsurancePayingToDeceasedYesNoID =  ihtPropertiesReader.getProperty("InsurancePayingToDeceasedYesNoID")
  lazy val InsurancePayingToDeceasedValueID =  ihtPropertiesReader.getProperty("InsurancePayingToDeceasedValueID")
  lazy val InsuranceJointlyHeldSectionID =  ihtPropertiesReader.getProperty("InsuranceJointlyHeldSectionID")
  lazy val InsuranceJointlyHeldYesNoID =  ihtPropertiesReader.getProperty("InsuranceJointlyHeldYesNoID")
  lazy val InsuranceJointlyHeldValueID =  ihtPropertiesReader.getProperty("InsuranceJointlyHeldValueID")
  lazy val InsurancePaidForSomeoneElseSectionID =  ihtPropertiesReader.getProperty("InsurancePaidForSomeoneElseSectionID")
  lazy val InsurancePaidForSomeoneElseYesNoID =  ihtPropertiesReader.getProperty("InsurancePaidForSomeoneElseYesNoID")
  lazy val InsurancePremiumnsYesNoID =  ihtPropertiesReader.getProperty("InsurancePremiumnsYesNoID")
  lazy val InsuranceAnnuityYesNoID =  ihtPropertiesReader.getProperty("InsuranceAnnuityYesNoID")
  lazy val InsurancePlacedInTrustYesNoID =  ihtPropertiesReader.getProperty("InsurancePlacedInTrustYesNoID")
  lazy val TnrbSpousePermanentHomeInUKID =  ihtPropertiesReader.getProperty("TnrbSpousePermanentHomeInUKID")
  lazy val TnrbGiftsGivenAwayID =  ihtPropertiesReader.getProperty("TnrbGiftsGivenAwayID")
  lazy val TnrbGiftsWithReservationID =  ihtPropertiesReader.getProperty("TnrbGiftsWithReservationID")
  lazy val TnrbEstateReliefID =  ihtPropertiesReader.getProperty("TnrbEstateReliefID")
  lazy val TnrbSpouseBenefitFromTrustID =  ihtPropertiesReader.getProperty("TnrbSpouseBenefitFromTrustID")
  lazy val TnrbEstatePassedToDeceasedID =  ihtPropertiesReader.getProperty("TnrbEstatePassedToDeceasedID")
  lazy val TnrbJointAssetsPassedToDeceasedID =  ihtPropertiesReader.getProperty("TnrbJointAssetsPassedToDeceasedID")
  lazy val TnrbSpouseMartialStatusID =  ihtPropertiesReader.getProperty("TnrbSpouseMartialStatusID")
  lazy val TnrbSpouseDateOfDeathID =  ihtPropertiesReader.getProperty("TnrbSpouseDateOfDeathID")
  lazy val TnrbSpouseNameID =  ihtPropertiesReader.getProperty("TnrbSpouseNameID")
  lazy val TnrbSpouseDateOfMarriageID =  ihtPropertiesReader.getProperty("TnrbSpouseDateOfMarriageID")
  lazy val AssetsPropertiesChangeID = ihtPropertiesReader.getProperty("AssetsPropertiesChangeID")
  lazy val AssetsPropertiesDeleteID = ihtPropertiesReader.getProperty("AssetsPropertiesDeleteID")
  lazy val AssetsPropertiesOwnedID = ihtPropertiesReader.getProperty("AssetsPropertiesOwnedID")
  lazy val AssetsPropertiesAddPropertyID = ihtPropertiesReader.getProperty("AssetsPropertiesAddPropertyID")
  lazy val AssetsPropertiesPropertyAddressID = ihtPropertiesReader.getProperty("AssetsPropertiesPropertyAddressID")
  lazy val AssetsPropertiesPropertyKindID = ihtPropertiesReader.getProperty("AssetsPropertiesPropertyKindID")
  lazy val AssetsPropertiesPropertyOwnershipID = ihtPropertiesReader.getProperty("AssetsPropertiesPropertyOwnershipID")
  lazy val AssetsPropertiesTenureID = ihtPropertiesReader.getProperty("AssetsPropertiesTenureID")
  lazy val AssetsPropertiesPropertyValueID = ihtPropertiesReader.getProperty("AssetsPropertiesPropertyValueID")
  lazy val AssetsMoneyOwnID = ihtPropertiesReader.getProperty("AssetsMoneyOwnID")
  lazy val AssetsMoneySharedID = ihtPropertiesReader.getProperty("AssetsMoneySharedID")
  lazy val AssetsVehiclesOwnID = ihtPropertiesReader.getProperty("AssetsVehiclesOwnID")
  lazy val AssetsVehiclesSharedID = ihtPropertiesReader.getProperty("AssetsVehiclesSharedID")
  lazy val AssetsStocksListedID = ihtPropertiesReader.getProperty("AssetsStocksListedID")
  lazy val AssetsStocksNotListedID = ihtPropertiesReader.getProperty("AssetsStocksNotListedID")
  lazy val AssetsHouseholdOwnID = ihtPropertiesReader.getProperty("AssetsHouseholdOwnID")
  lazy val AssetsHouseholdSharedID = ihtPropertiesReader.getProperty("AssetsHouseholdSharedID")
  lazy val AssetsPensionsOwnedID = ihtPropertiesReader.getProperty("AssetsPensionsOwnedID")
  lazy val AssetsPensionChangesID = ihtPropertiesReader.getProperty("AssetsPensionChangesID")
  lazy val AssetsPensionsValueID = ihtPropertiesReader.getProperty("AssetsPensionsValueID")
  lazy val AssetsTrustsBenefitedID = ihtPropertiesReader.getProperty("AssetsTrustsBenefitedID")
  lazy val AssetsTrustsMultipleID = ihtPropertiesReader.getProperty("AssetsTrustsMultipleID")
  lazy val AssetsTrustsValueID = ihtPropertiesReader.getProperty("AssetsTrustsValueID")
  lazy val DebtsMortgagesPropertyID = ihtPropertiesReader.getProperty("DebtsMortgagesPropertyID")
  lazy val ExemptionsPartnerID = ihtPropertiesReader.getProperty("ExemptionsPartnerID")
  lazy val ExemptionsCharityID = ihtPropertiesReader.getProperty("ExemptionsCharityID")
  lazy val ExemptionsOtherID = ihtPropertiesReader.getProperty("ExemptionsOtherID")
  lazy val ExemptionsPartnerAssetsID = ihtPropertiesReader.getProperty("ExemptionsPartnerAssetsID")
  lazy val ExemptionsPartnerHomeID = ihtPropertiesReader.getProperty("ExemptionsPartnerHomeID")
  lazy val ExemptionsPartnerNameID = ihtPropertiesReader.getProperty("ExemptionsPartnerNameID")
  lazy val ExemptionsPartnerDobID = ihtPropertiesReader.getProperty("ExemptionsPartnerDobID")
  lazy val ExemptionsPartnerNinoID = ihtPropertiesReader.getProperty("ExemptionsPartnerNinoID")
  lazy val ExemptionsPartnerValueID = ihtPropertiesReader.getProperty("ExemptionsPartnerValueID")
  lazy val ExemptionsCharitiesAssetsID = ihtPropertiesReader.getProperty("ExemptionsCharitiesAssetsID")
  lazy val ExemptionsCharitiesDeleteID = ihtPropertiesReader.getProperty("ExemptionsCharitiesDeleteID")
  lazy val ExemptionsCharitiesChangeID = ihtPropertiesReader.getProperty("ExemptionsCharitiesChangeID")
  lazy val ExemptionsCharitiesAddID = ihtPropertiesReader.getProperty("ExemptionsCharitiesAddID")
  lazy val ExemptionsCharitiesNameID = ihtPropertiesReader.getProperty("ExemptionsCharitiesNameID")
  lazy val ExemptionsCharitiesNumberID = ihtPropertiesReader.getProperty("ExemptionsCharitiesNumberID")
  lazy val ExemptionsCharitiesValueID = ihtPropertiesReader.getProperty("ExemptionsCharitiesValueID")
  lazy val ExemptionsOtherAssetsID = ihtPropertiesReader.getProperty("ExemptionsOtherAssetsID")
  lazy val ExemptionsOtherDeleteID = ihtPropertiesReader.getProperty("ExemptionsOtherDeleteID")
  lazy val ExemptionsOtherChangeID = ihtPropertiesReader.getProperty("ExemptionsOtherChangeID")
  lazy val ExemptionsOtherAddID = ihtPropertiesReader.getProperty("ExemptionsOtherAddID")
  lazy val ExemptionsOtherNameID = ihtPropertiesReader.getProperty("ExemptionsOtherNameID")
  lazy val ExemptionsOtherValueID = ihtPropertiesReader.getProperty("ExemptionsOtherValueID")
  lazy val EstateAssetsID = ihtPropertiesReader.getProperty("EstateAssetsID")
  lazy val EstateGiftsID = ihtPropertiesReader.getProperty("EstateGiftsID")
  lazy val EstateDebtsID = ihtPropertiesReader.getProperty("EstateDebtsID")
  lazy val EstateExemptionsID = ihtPropertiesReader.getProperty("EstateExemptionsID")
  lazy val EstateIncreasingID = ihtPropertiesReader.getProperty("EstateIncreasingID")
}
